Repository iammatis/iKalendar, pull requests merged in 2021-04, with the labels that each got.

#66 Fix #65 vulnerabilities
  package-lock.json
Labels: chore

#58 Make parsing an empty string return an empty string, fixes #57
  src/parser/properties/string.parser.ts
  tests/parser/string.parser.test.ts
Labels: bug, parser

#68 Update #67 package contributors
  package.json
Labels: chore, documentation

#71 1.2.0
  package-lock.json
  package.json
Labels: chore

#70 Release 1.2.0 #69
  package-lock.json
  package.json
  src/parser/properties/string.parser.ts
  tests/parser/string.parser.test.ts
Labels: chore

#78 Update #77 package.json dependencies
  .eslintrc
  package-lock.json
  package.json
  src/parser/properties/string.parser.ts
  src/types/classes/parsers/property.parser.ts
  src/types/components/freebusy.ts
Labels: chore

#80 Update #74 version to 1.3.0
  package-lock.json
  package.json
Labels: chore

#79 Release 1.3.0
  .eslintrc
  package-lock.json
  package.json
  src/builder.ts
  src/parser/properties/string.parser.ts
  src/types/classes/parsers/property.parser.ts
  src/types/components/freebusy.ts
Labels: chore
